version: '3.7'

services:
  postgres:
    build: ./pg_storage
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: designer
      POSTGRES_PASSWORD: gh5vMBSuLThnaZWrKf
      POSTGRES_DB: shoredurls

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  go-app:
    build: ./service
    environment:
      APP_PORT: 8080
      REDIS_CONN_URL: ""
      PG_CONN_URL: ""
      USE_ONLY_IN_MEMORY_STORAGE: ""
    ports:
      - "8080:8080"

volumes:
  pgdata:
  redisdata:
